# Variáveis para facilitar os testes
@baseUrl = http://localhost:3000

###
# (1) POST - Criar novos Patrimônios
# Execute estas requisições primeiro para popular os dados em memória.
# Se você estiver usando a extensão REST Client no VSCode, clique em "Send Request" acima de cada uma.

# Criar o primeiro patrimônio
POST {{baseUrl}}/patrimonios
Content-Type: application/json

{
  "nome": "Monitor Dell 24 polegadas",
  "numeroPatrimonio": 1001,
  "descricao": "Monitor Full HD para desenvolvimento",
  "valor": 1200.50,
  "responsavel": "Alice Silva",
  "status": "ativo",
  "localizacao": {
    "bloco": "R",
    "piso": "3",
    "sala": "301"
  }
}

###
# Criar o patrimônio inválido
POST {{baseUrl}}/patrimonios
Content-Type: application/json

{
  "nome": "",
  "numeroPatrimonio": "abc",
  "descricao": 0,
  "valor": "invalid", 
  "responsavel": 0,
  "status": "invalid",
  "observacoes": 0,
  "localizacao": {
    "bloco": "",
    "piso": 0,
    "sala": 0
  }
}

###
# Criar patrimônio inativo
POST {{baseUrl}}/patrimonios
Content-Type: application/json

{
  "nome": "Monitor Dell 20 polegadas",
  "numeroPatrimonio": 900,
  "descricao": "Monitor Full HD para desenvolvimento",
  "valor": 1100.50,
  "responsavel": "Pedro Silva",
  "status": "inativo",
  "localizacao": {
    "bloco": "R",
    "piso": "2",
    "sala": "201"
  }
}

###
# (2) GET - Listar Patrimônios com Filtro e Paginação
###
# Listar patrimônios com status "inativo"
GET {{baseUrl}}/patrimonios?status=inativo

###
# Listar patrimônios por id
GET {{baseUrl}}/patrimonios/1

###
# Listar patrimônios combinando filtros
GET {{baseUrl}}/patrimonios?status=ativo&filtro=dell

###
# Listar patrimônios com paginação (página 1, limite de 2 por página)
GET {{baseUrl}}/patrimonios?page=1&limit=2


###
# (3) GET - Buscar um Patrimônio específico pelo ID
# Lembre-se que o ID é sequencial (1, 2, 3...)
GET {{baseUrl}}/patrimonios/1


###
# (4) PUT - Atualizar COMPLETAMENTE um Patrimônio
# O método PUT exige que todos os campos obrigatórios sejam enviados.
PUT {{baseUrl}}/patrimonios/1
Content-Type: application/json

{
  "nome": "Monitor Dell 24p (Atualizado)",
  "numeroPatrimonio": 1001,
  "descricao": "Monitor Full HD para desenvolvimento",
  "valor": 1150.00,
  "responsavel": "Carlos Pereira",
  "status": "inativo",
  "localizacao": {
    "bloco": "B",
    "andar": "3",
    "sala": "302"
  }
}


###
# (5) PATCH - Atualizar PARCIALMENTE um Patrimônio
# O método PATCH permite enviar apenas os campos que você quer alterar.
PATCH {{baseUrl}}/patrimonios/2
Content-Type: application/json

{
  "status": "ativo",
  "observacoes": "Conserto finalizado."
}


###
# (6) DELETE - Remover um Patrimônio
DELETE {{baseUrl}}/patrimonios/3